import * as Lucide from 'lucide-react-native';
import { ComponentType } from 'react';

const iconMap: Record<string, ComponentType<{ size?: number; color?: string }>> = {
  Briefcase: Lucide.Briefcase,
  Laptop: Lucide.Laptop,
  TrendingUp: Lucide.TrendingUp,
  Gift: Lucide.Gift,
  DollarSign: Lucide.DollarSign,
  UtensilsCrossed: Lucide.UtensilsCrossed,
  Car: Lucide.Car,
  ShoppingBag: Lucide.ShoppingBag,
  Film: Lucide.Film,
  FileText: Lucide.FileText,
  Heart: Lucide.Heart,
  GraduationCap: Lucide.GraduationCap,
  Dumbbell: Lucide.Dumbbell,
  MoreHorizontal: Lucide.MoreHorizontal,
  Wallet: Lucide.Wallet,
  Building2: Lucide.Building2,
  CreditCard: Lucide.CreditCard,
  Home: Lucide.Home,
  Zap: Lucide.Zap,
  Music: Lucide.Music,
  Plane: Lucide.Plane,
  Train: Lucide.Train,
  Coffee: Lucide.Coffee,
  Pizza: Lucide.Pizza,
  Shirt: Lucide.Shirt,
  Smartphone: Lucide.Smartphone,
  Gamepad2: Lucide.Gamepad2,
  Book: Lucide.Book,
  Bike: Lucide.Bike,
  Trees: Lucide.Trees,
  PawPrint: Lucide.PawPrint,
  Baby: Lucide.Baby,
  Palette: Lucide.Palette,
  Handshake: Lucide.Handshake,
  Landmark: Lucide.Landmark,
  Banknote: Lucide.Banknote,
  Coins: Lucide.Coins,
  PiggyBank: Lucide.PiggyBank,
  BadgeDollarSign: Lucide.BadgeDollarSign,
  CircleDollarSign: Lucide.CircleDollarSign,
  Edit2: Lucide.Pencil,
  Pencil: Lucide.Pencil,
  Trash2: Lucide.Trash2,
  Trash: Lucide.Trash2,
  Circle: Lucide.Circle,
  Plus: Lucide.Plus,
  Calendar: Lucide.Calendar,
  ChevronRight: Lucide.ChevronRight,
  Search: Lucide.Search,
  SlidersHorizontal: Lucide.SlidersHorizontal,
  X: Lucide.X,
  Receipt: Lucide.Receipt,
  Settings: Lucide.Settings,
  TrendingDown: Lucide.TrendingDown,
};

export function getIcon(name: string): ComponentType<{ size?: number; color?: string }> {
  return iconMap[name] || Lucide.Circle;
}
